spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/YOUTH
    password: lalorsh6471!

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'

  servlet:
    multipart:
      file-size-threshold: 1MB
      location: /Users/laykis/Desktop/Temp
      max-file-size: 100MB
      max-request-size: 100MB